DROP TABLE IF EXISTS Comments;

DROP TABLE IF EXISTS EventStore;

CREATE TABLE Comments (
  id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL
);

CREATE TABLE EventStore (
  event_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  event VARCHAR(20) NOT NULL,
  event_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  comment_id INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL
);